{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e5bc77be-bb96-4e0e-bd7b-05dc16c86fdb",
   "metadata": {},
   "outputs": [],
   "source": [
    "!pip install -U nbdev"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "f9a4f48d-ede6-4f94-b7a8-b77d42e92a46",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[33mWARNING: The directory '/home/jovyan/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.\u001b[0m\u001b[33m\n",
      "\u001b[0mCollecting pyngrok\n",
      "  Downloading pyngrok-7.0.0.tar.gz (718 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m718.7/718.7 kB\u001b[0m \u001b[31m39.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hRequirement already satisfied: PyYAML in /opt/conda/lib/python3.11/site-packages (from pyngrok) (6.0.1)\n",
      "Building wheels for collected packages: pyngrok\n",
      "  Building wheel for pyngrok (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for pyngrok: filename=pyngrok-7.0.0-py3-none-any.whl size=21129 sha256=746fca56f48eb2a1b92eff9c04210688ad33598f6cbfc9d07768b697a3f47ee6\n",
      "  Stored in directory: /tmp/pip-ephem-wheel-cache-iajrcv6n/wheels/01/28/9c/5a79fae0cdb145a341b220ed41a4ecf660eec07b9090e17c16\n",
      "Successfully built pyngrok\n",
      "Installing collected packages: pyngrok\n",
      "Successfully installed pyngrok-7.0.0\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "!pip install pyngrok"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "8f928d31-632a-4ee3-878e-b9199bc4d7b2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Authtoken saved to configuration file: /home/jovyan/.config/ngrok/ngrok.yml                         \n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<NgrokTunnel: \"https://9a72-172-83-13-4.ngrok-free.app\" -> \"http://localhost:7000\">"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from pyngrok import ngrok\n",
    "!ngrok config add-authtoken 2TcZn9S1EnAWRznc1F3l07EhsDA_5DKkTteGNdVniRR6JMcAU\n",
    "ngrok_tunnel = ngrok.connect(7000)\n",
    "\n",
    "ngrok_tunnel"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "b2e4dd8e-177d-472d-9e5f-796870f2a39d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Quarto is not installed. We will download and install it for you.\n",
      "Installing or upgrading quarto -- this requires root access.\n",
      "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n",
      "                                 Dload  Upload   Total   Spent    Left  Speed\n",
      "100    72  100    72    0     0    576      0 --:--:-- --:--:-- --:--:--   580\n",
      "100   114    0   114    0     0    624      0 --:--:-- --:--:-- --:--:--   624\n",
      "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\n",
      "100 84.5M  100 84.5M    0     0  97.3M      0 --:--:-- --:--:-- --:--:-- 97.3M\n",
      "Selecting previously unselected package quarto.\n",
      "(Reading database ... 47195 files and directories currently installed.)\n",
      "Preparing to unpack quarto-linux-amd64.deb ...\n",
      "Unpacking quarto (1.3.450) ...\n",
      "Setting up quarto (1.3.450) ...\n",
      "\u001b[33mWARNING: The directory '/home/jovyan/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.\u001b[0m\u001b[33m\n",
      "\u001b[0mObtaining file:///notebooks/nbs\n",
      "\u001b[31mERROR: file:///notebooks/nbs does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.\u001b[0m\u001b[31m\n",
      "\u001b[0m\u001b[1m\u001b[34mPreparing to preview\u001b[39m\u001b[22m\n",
      "[1/3] index.ipynb\u001b[39m\u001b[22m\n",
      "[2/3] setup.ipynb\u001b[39m\u001b[22m\n",
      "[3/3] notebooks/AlphaMissense_to_pdb.ipynb\u001b[39m\u001b[22m\n",
      "\n",
      "\u001b[32mWatching files for changes\u001b[39m\n",
      "\u001b[32mBrowse at \u001b[39m\u001b[4m\u001b[32mhttp://localhost:7000/\u001b[39m\u001b[24m\n",
      "/usr/bin/xdg-open: 882: www-browser: not found\n",
      "/usr/bin/xdg-open: 882: links2: not found\n",
      "/usr/bin/xdg-open: 882: elinks: not found\n",
      "/usr/bin/xdg-open: 882: links: not found\n",
      "/usr/bin/xdg-open: 882: lynx: not found\n",
      "/usr/bin/xdg-open: 882: w3m: not found\n",
      "xdg-open: no method available for opening 'http://localhost:7000/'\n",
      "\u001b[32mGET: /\u001b[39m\n",
      "\u001b[32mGET: /\u001b[39m\n",
      "\u001b[32mGET: /\u001b[39m\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "\u001b[1mpandoc \u001b[22m\n",
      "  to: html\n",
      "  output-file: setup.html\n",
      "  standalone: true\n",
      "  title-prefix: nbs\n",
      "  section-divs: true\n",
      "  html-math-method: mathjax\n",
      "  wrap: none\n",
      "  default-image-extension: png\n",
      "  css:\n",
      "    - styles.css\n",
      "  toc: true\n",
      "  \n",
      "\u001b[1mmetadata\u001b[22m\n",
      "  document-css: false\n",
      "  link-citations: true\n",
      "  date-format: long\n",
      "  lang: en\n",
      "  theme: cosmo\n",
      "  \n",
      "\u001b[32mGET: /setup.html\u001b[39m\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "\u001b[32mGET: /setup.html\u001b[39m\n",
      "\u001b[32mGET: /notebooks/r_sample.html\u001b[39m\n",
      "\u001b[1mpandoc \u001b[22m\n",
      "  to: html\n",
      "  output-file: setup.html\n",
      "  standalone: true\n",
      "  title-prefix: nbs\n",
      "  section-divs: true\n",
      "  html-math-method: mathjax\n",
      "  wrap: none\n",
      "  default-image-extension: png\n",
      "  css:\n",
      "    - styles.css\n",
      "  toc: true\n",
      "  \n",
      "\u001b[1mmetadata\u001b[22m\n",
      "  document-css: false\n",
      "  link-citations: true\n",
      "  date-format: long\n",
      "  lang: en\n",
      "  theme: cosmo\n",
      "  \n",
      "\u001b[32mGET: /setup.html\u001b[39m\n",
      "\u001b[32mGET: /notebooks/r_sample.html\u001b[39m\n",
      "\u001b[1mpandoc \u001b[22m\n",
      "  to: html\n",
      "  output-file: /notebooks/nbs/_proc/notebooks/r_sample.html\n",
      "  standalone: true\n",
      "  title-prefix: nbs\n",
      "  section-divs: true\n",
      "  html-math-method: mathjax\n",
      "  wrap: none\n",
      "  default-image-extension: png\n",
      "  css:\n",
      "    - ../styles.css\n",
      "  toc: true\n",
      "  \n",
      "\u001b[1mmetadata\u001b[22m\n",
      "  document-css: false\n",
      "  link-citations: true\n",
      "  date-format: long\n",
      "  lang: en\n",
      "  theme: cosmo\n",
      "  title: R\n",
      "  \n",
      "\u001b[32mGET: /notebooks/r_sample.html\u001b[39m\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/quarto.py\", line 297, in _f\n",
      "    try: serve_drv.main(res)\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 22, in main\n",
      "    if src.suffix=='.ipynb': exec_nb(src, dst, x)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/nbdev/serve_drv.py\", line 15, in exec_nb\n",
      "    nb = read_nb(src)\n",
      "         ^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 57, in read_nb\n",
      "    res = dict2nb(_read_json(path, encoding='utf-8'))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/site-packages/execnb/nbio.py\", line 16, in _read_json\n",
      "    return loads(Path(self).read_text(encoding=encoding, errors=errors))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "\u001b[1mpandoc \u001b[22m\n",
      "  to: html\n",
      "  output-file: /notebooks/nbs/_proc/notebooks/r_sample.html\n",
      "  standalone: true\n",
      "  title-prefix: nbs\n",
      "  section-divs: true\n",
      "  html-math-method: mathjax\n",
      "  wrap: none\n",
      "  default-image-extension: png\n",
      "  css:\n",
      "    - ../styles.css\n",
      "  toc: true\n",
      "  \n",
      "\u001b[1mmetadata\u001b[22m\n",
      "  document-css: false\n",
      "  link-citations: true\n",
      "  date-format: long\n",
      "  lang: en\n",
      "  theme: cosmo\n",
      "  title: R\n",
      "  \n",
      "\u001b[32mGET: /notebooks/r_sample.html\u001b[39m\n",
      "\u001b[91mERROR: \n",
      "Error reading metadata file from /notebooks/nbs/_proc/sidebar.yml\n",
      "\u001b[39m\n",
      "\u001b[91mERROR: Internal Error: createSourceContext called with bad location.\n",
      "\n",
      "Error: Internal Error: createSourceContext called with bad location.\n",
      "    at createSourceContext (file:///opt/quarto/bin/quarto.js:14790:15)\n",
      "    at createLocalizedError (file:///opt/quarto/bin/quarto.js:14864:28)\n",
      "    at file:///opt/quarto/bin/quarto.js:15006:55\n",
      "    at Array.map (<anonymous>)\n",
      "    at ValidationContext.collectErrors (file:///opt/quarto/bin/quarto.js:15006:32)\n",
      "    at ValidationContext.validate (file:///opt/quarto/bin/quarto.js:14929:21)\n",
      "    at validate (file:///opt/quarto/bin/quarto.js:15293:20)\n",
      "    at YAMLSchema.validateParse (file:///opt/quarto/bin/quarto.js:15318:34)\n",
      "    at validate (file:///opt/quarto/bin/quarto.js:18623:43)\n",
      "    at withValidator (file:///opt/quarto/bin/quarto.js:15381:25)\u001b[39m\n",
      "^C\n"
     ]
    }
   ],
   "source": [
    "!nbdev_preview --port 7000"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "102218a6-8643-49c4-9a96-f2d5917bea26",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
